name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -PTEST --file pom.xml
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}/target
    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and Push Docker Image to DockerHub
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        context: ${{ github.workspace }}
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
    - name: Deploy on Server
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: -a pretixtonextcloudintegrator -e development -t latest
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        privateKey: ${{ secrets.DEPLOYMENT_SSH_KEY }}