name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        concurrency: [1]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout Library - java-utilities
      uses: actions/checkout@v4
      with:
        repository: derBobby/java-utilities
        ref: main
        path: java-utilities
    - name: Checkout Library - java-nextcloud-connector
      uses: actions/checkout@v4
      with:
        repository: derBobby/java-nextcloud-connector
        ref: main
        path: java-nextcloud-connector

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Library - java-utilities
      working-directory: ${{ github.workspace }}/java-utilities
      run: |
        mvn clean install
    - name: Install Library - java-nextcloud-connector
      working-directory: ${{ github.workspace }}/java-nextcloud-connector
      run: |
        mvn clean install

    - name: Build with Maven
      run: mvn -B package -PTEST --file pom.xml
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}/target
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Build and Push Docker Image to DockerHub
      uses: docker/build-push-action@v5.0.0
      with:
        push: true
        context: ${{ github.workspace }}
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
    - name: Deploy on Server
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: -a pretixtonextcloudintegrator -e staging -t latest
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        privateKey: ${{ secrets.DEPLOYMENT_SSH_KEY }}
