name: Deploy to staging

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        concurrency: [1]

    steps:
    - name: Checkout Git
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --file pom.xml install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and Push Docker Image to DockerHub
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        context: ${{ github.workspace }}
        tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

    - name: Deploy on Server
      uses: garygrossgarten/github-action-ssh@0.7.0
      with:
        command: -a pretixtonextcloudintegrator -e staging -t latest
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        port: ${{ secrets.DEPLOYMENT_PORT }}
        privateKey: ${{ secrets.DEPLOYMENT_SSH_KEY }}
