name: Deploy to staging

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        options:
          - development
          - staging
          - production
        required: true
        # TODO can be environment. Advantages?
        type: choice
        description: Environment to which the deployment is done.
env:
  environment: ${{ inputs.environment || 'staging' }}

jobs:
  mvn-publish:
    uses: derBobby/java-pipelines/.github/workflows/callable-mvn.yml@main
    with:
      mvn-stage: deploy
      cache-jar: true
  codeql:
    needs: mvn-publish
    uses: derBobby/java-pipelines/.github/workflows/callable-codeql.yml@main
  docker:
    needs: mvn-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
      # TODO this job must have knowledge about called job. How to solve this?
      - name: Download JAR from cache
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ runner.os }}-jar-${{ hashFiles('target/*.jar') }}
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image to DockerHub
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          context: ${{ github.workspace }}
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest
      - name: Deploy on Server
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          command: -a p2nc-integrator -e ${{ env.environment }} -t latest
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          privateKey: ${{ secrets.DEPLOYMENT_SSH_KEY }}